version: "3.9"
networks:
  kong-net:
services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: on-failure
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
  kong-migrations:
    image: kong/kong-gateway:3.2.2.1
    command: kong migrations bootstrap
    container_name: kong
    restart: on-failure
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    depends_on:
      - kong-database

  kong-gateway:
    image: kong/kong-gateway:3.2.2.1
    container_name: kong-gateway
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-net
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga
    container_name: konga
    restart: on-failure
    networks:
      - kong-net
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway
      # http://kong-gateway:8001
      # host.docker.internal or localhost or service name
